// Matched on this prefix alone, never on the whole BEGIN line. The rest of the
// line is attribution prose, and prose gets corrected: blocks written by older
// CLI versions are already on disk in every onboarded repository, and matching
// the full literal would stop recognising them the moment the wording changed —
// so the next run would append a second block beside the first instead of
// replacing it.
export const BEGIN_PREFIX = '<!-- REDLINE:BEGIN';
export const BEGIN = `${BEGIN_PREFIX} — generated by Redline. Do not edit inside this block. -->`;
export const END = '<!-- REDLINE:END -->';

export function wrapBlock(existing: string | null, body: string): string {
  const block = `${BEGIN}\n\n${body.trimEnd()}\n\n${END}\n`;
  if (existing === null) return block;
  const start = existing.indexOf(BEGIN_PREFIX);
  const stop = existing.indexOf(END);
  if (start === -1 || stop === -1) return `${existing.trimEnd()}\n\n${block}`;
  return existing.slice(0, start) + block.trimEnd() + existing.slice(stop + END.length);
}
