export const BEGIN =
  '<!-- REDLINE:BEGIN — generated by scripts/render.mjs. Do not edit inside this block. -->';
export const END = '<!-- REDLINE:END -->';

export function wrapBlock(existing: string | null, body: string): string {
  const block = `${BEGIN}\n\n${body.trimEnd()}\n\n${END}\n`;
  if (existing === null) return block;
  const start = existing.indexOf(BEGIN);
  const stop = existing.indexOf(END);
  if (start === -1 || stop === -1) return `${existing.trimEnd()}\n\n${block}`;
  return existing.slice(0, start) + block.trimEnd() + existing.slice(stop + END.length);
}
