import { test } from 'node:test';
import assert from 'node:assert/strict';
import { isRedlineError } from '../../core/errors.ts';
import { BEGIN, BEGIN_PREFIX, END, findBlock, wrapBlock } from '../markers.ts';

const LABEL = '.github/pull_request_template.md';
const wrap = (existing: string | null, body: string): string => wrapBlock(existing, body, LABEL);

const malformed = (existing: string | null, body = 'NEW'): { message: string; exitCode: number } => {
  try {
    wrap(existing, body);
  } catch (error) {
    assert.ok(isRedlineError(error), 'a malformed marker pair must fail as a RedlineError');
    return { message: error.message, exitCode: error.exitCode };
  }
  throw new Error('expected wrapBlock to refuse the file');
};

test('the marker strings are byte-exact', () => {
  assert.equal(BEGIN_PREFIX, '<!-- REDLINE:BEGIN');
  assert.equal(BEGIN, '<!-- REDLINE:BEGIN — generated by Redline. Do not edit inside this block. -->');
  assert.equal(END, '<!-- REDLINE:END -->');
});

test('no existing file yields the block alone', () => {
  assert.equal(wrap(null, 'rules'), `${BEGIN}\n\nrules\n\n${END}\n`);
});

test('an existing file without markers keeps its content and gains the block', () => {
  const out = wrap('# My repo\n\nHand-written.\n', 'rules');
  assert.equal(out, `# My repo\n\nHand-written.\n\n${BEGIN}\n\nrules\n\n${END}\n`);
});

test('an existing block is replaced and surrounding content preserved', () => {
  const existing = `before\n\n${BEGIN}\n\nOLD\n\n${END}\n\nafter\n`;
  const out = wrap(existing, 'NEW');
  assert.equal(out, `before\n\n${BEGIN}\n\nNEW\n\n${END}\n\nafter\n`);
  assert.ok(!out.includes('OLD'));
});

test('content after the end marker survives verbatim, including a second heading', () => {
  const existing = `${BEGIN}\n\nOLD\n\n${END}\n\n## Repo-owned section\n\nkeep me\n`;
  assert.match(wrap(existing, 'NEW'), /## Repo-owned section\n\nkeep me\n$/);
});

test('the body is right-trimmed before wrapping', () => {
  assert.equal(wrap(null, 'rules\n\n\n'), `${BEGIN}\n\nrules\n\n${END}\n`);
});

test('running wrapBlock twice with the same body is idempotent', () => {
  const first = wrap('before\n\nhand-written\n', 'rules');
  assert.equal(wrap(first, 'rules'), first);
});

// The marker text is attribution prose, and it has already been wrong once: it
// named scripts/render.mjs while the CLI's install path writes blocks too.
// Matching on the whole literal makes every future correction a live migration
// hazard — the blocks already on disk in every onboarded repository stop
// matching, and the next run appends a SECOND block beside the first.
test('a block whose BEGIN line differs in its trailing prose is replaced, not duplicated', () => {
  const stale = '<!-- REDLINE:BEGIN — generated by scripts/render.mjs. Do not edit inside this block. -->';
  const out = wrap(`before\n\n${stale}\n\nOLD\n\n${END}\n\nafter\n`, 'NEW');
  assert.equal(out, `before\n\n${BEGIN}\n\nNEW\n\n${END}\n\nafter\n`);
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1, 'exactly one BEGIN marker must survive');
  assert.ok(!out.includes(stale));
});

test('a block written under an older marker text is recognised as owned, not appended to', () => {
  const out = wrap(`<!-- REDLINE:BEGIN — something else entirely -->\n\nOLD\n\n${END}\n`, 'NEW');
  assert.equal(out.split(END).length - 1, 1, 'exactly one END marker must survive');
  assert.ok(out.startsWith(BEGIN));
});

// --- malformed marker pairs. Redline cannot tell which span it owns, so it
// must not guess: no silent repair, no second block, no deletion. Refuse and
// name the file. wrapBlock also writes CLAUDE.md, AGENTS.md and
// .github/copilot-instructions.md in every onboarded repository, so a wrong
// guess here corrupts files across the whole estate, not just this one.

test('END before BEGIN is refused instead of duplicating the span on every run', () => {
  const { message, exitCode } = malformed(`head\n\n${END}\n\nmiddle\n\n${BEGIN}\n\ntail\n`);
  assert.match(message, /pull_request_template\.md/, 'the message must name the file');
  assert.match(message, /REDLINE:END/);
  assert.match(message, /before/);
  assert.equal(exitCode, 1);
});

test('a BEGIN marker with no END is refused instead of losing user content on the second run', () => {
  const { message, exitCode } = malformed(`A\n\n${BEGIN}\n\nUSER STUFF\n`);
  assert.match(message, /pull_request_template\.md/);
  assert.match(message, /REDLINE:BEGIN/);
  assert.equal(exitCode, 1);
});

test('an END marker with no BEGIN is refused', () => {
  const { message } = malformed(`A\n\n${END}\n\nB\n`);
  assert.match(message, /REDLINE:END/);
});

test('two BEGIN markers are refused rather than the first one silently winning', () => {
  const { message } = malformed(`${BEGIN}\n\nONE\n\n${BEGIN}\n\nTWO\n\n${END}\n`);
  assert.match(message, /pull_request_template\.md/);
});

test('two END markers are refused rather than the first one silently winning', () => {
  const { message } = malformed(`${BEGIN}\n\nONE\n\n${END}\n\nmid\n\n${END}\n`);
  assert.match(message, /pull_request_template\.md/);
});

test('a refused file is reported with a hint that tells a human how to fix their own file', () => {
  try {
    wrap(`${BEGIN}\n\nno end\n`, 'NEW');
    throw new Error('expected a refusal');
  } catch (error) {
    assert.ok(isRedlineError(error));
    assert.match(error.hint ?? '', /REDLINE:BEGIN/);
  }
});

// --- a marker quoted rather than written. Matching on the prefix widened this
// sink: any quoted marker text, current or historical, used to be a live target.

test('a marker quoted mid-line in prose is not mistaken for the block', () => {
  const existing = `Docs say the block starts at \`${BEGIN_PREFIX}\` and ends at \`${END}\`.\n`;
  const out = wrap(existing, 'NEW');
  assert.ok(out.startsWith(existing), 'the prose must survive verbatim');
  assert.ok(out.endsWith(`${BEGIN}\n\nNEW\n\n${END}\n`), 'the block is appended, not spliced into the prose');
});

test('a marker inside a fenced code block is not mistaken for the block, and the real one is replaced', () => {
  const existing =
    `# Docs\n\nOur convention:\n\n\`\`\`md\n${BEGIN}\n\nEXAMPLE\n\n${END}\n\`\`\`\n\n` +
    `HUMAN SECTION A\n\n${BEGIN}\n\nOLD\n\n${END}\n\nTail\n`;

  const out = wrap(existing, 'NEW');

  assert.match(out, /HUMAN SECTION A/, 'content between the fence and the real block must survive');
  assert.match(out, /EXAMPLE/, 'the fenced illustration must survive');
  assert.match(out, /Tail\n$/);
  assert.ok(!out.includes('OLD'));
  assert.equal(out.split('NEW').length - 1, 1);
});

test('a tilde-fenced marker is skipped too, and a longer closing fence still closes', () => {
  const existing = `~~~~\n${BEGIN}\nEXAMPLE\n${END}\n~~~~\n\nreal:\n\n${BEGIN}\n\nOLD\n\n${END}\n`;
  const out = wrap(existing, 'NEW');
  assert.match(out, /EXAMPLE/);
  assert.ok(!out.includes('OLD'));
});

// --- byte-level boundaries.

test('an empty file gets the block alone, with no leading blank lines', () => {
  assert.equal(wrap('', 'rules'), `${BEGIN}\n\nrules\n\n${END}\n`);
});

test('a file with no trailing newline keeps its last byte and is separated from the block', () => {
  assert.equal(wrap('X', 'rules'), `X\n\n${BEGIN}\n\nrules\n\n${END}\n`);
});

test('trailing blank lines in the human file are preserved, not trimmed away', () => {
  const existing = 'keep\n\n\n\n';
  const out = wrap(existing, 'rules');
  assert.ok(out.startsWith(existing), 'the append path must be byte-for-byte on the existing content');
  assert.equal(out, `${existing}${BEGIN}\n\nrules\n\n${END}\n`);
});

test('a CRLF file keeps its line endings outside the block on both the append and replace paths', () => {
  const appended = wrap('# Repo\r\n\r\nHand-written.\r\n', 'rules');
  assert.ok(appended.startsWith('# Repo\r\n\r\nHand-written.\r\n'), 'CRLF content must survive verbatim');
  assert.ok(appended.endsWith(`${BEGIN}\n\nrules\n\n${END}\n`));

  const replaced = wrap(`before\r\n\r\n${BEGIN}\r\n\r\nOLD\r\n\r\n${END}\r\n\r\nafter\r\n`, 'NEW');
  assert.ok(replaced.startsWith('before\r\n\r\n'));
  assert.ok(replaced.endsWith('\r\n\r\nafter\r\n'));
  assert.ok(!replaced.includes('OLD'));
});

test('findBlock reports no block for a file that has never been touched', () => {
  assert.equal(findBlock('# Repo\n\nnothing here\n', LABEL), null);
});

// --- unresolvable fencing. CommonMark: "If the end of the document is reached
// and no closing code fence has been found, the code block contains all of the
// lines after the opening code fence." So an unclosed fence is valid markdown,
// not a mangled file — and it hides every marker below it from the scan. Reading
// those markers as absent appends a second block on every run; reading them as
// real splices inside what renders as a code block. Both are guesses about a
// human-owned file.

test('an unclosed code fence hiding the block is refused, not appended to on every run', () => {
  const existing = `# Docs\n\nOur convention:\n\n\`\`\`md\n${BEGIN}\n\nOLD\n\n${END}\n`;
  const { message, exitCode } = malformed(existing);
  assert.match(message, /pull_request_template\.md/);
  assert.match(message, /unclosed code fence/);
  assert.equal(exitCode, 1);
});

test('the unclosed-fence refusal points at the line that opened the fence', () => {
  try {
    wrap(`one\ntwo\n\`\`\`\n${BEGIN}\n${END}\n`, 'NEW');
    throw new Error('expected a refusal');
  } catch (error) {
    assert.ok(isRedlineError(error));
    assert.match(error.hint ?? '', /line 3/);
    assert.match(error.hint ?? '', /Redline made no change to that file/);
  }
});

// Precision: with no marker in the undecidable region the two readings agree, so
// nothing is being guessed and there is nothing to refuse. Unclosed fences are
// common enough by accident that refusing every one would be gratuitous.
test('an unclosed fence with no markers below it is not a refusal and the real block still replaces', () => {
  const existing = `${BEGIN}\n\nOLD\n\n${END}\n\n# Notes\n\n\`\`\`sh\nnever closed\n`;
  const out = wrap(existing, 'NEW');
  assert.equal(out, `${BEGIN}\n\nNEW\n\n${END}\n\n# Notes\n\n\`\`\`sh\nnever closed\n`);
  assert.equal(wrap(out, 'NEW'), out, 'and it is stable across a second run');
});

test('a fence opened inside the marked block is refused rather than silently swallowing the END', () => {
  const { message } = malformed(`${BEGIN}\n\n\`\`\`\nOLD\n\n${END}\n\nafter\n`);
  assert.match(message, /unclosed code fence/);
});

// CommonMark: "The closing code fence ... may not have an info string." A
// ```md line inside an open ``` fence is content, not the close.
test('a closing fence carrying an info string does not close the fence', () => {
  const { message } = malformed(`\`\`\`\nexample:\n\`\`\`md\n${BEGIN}\nX\n${END}\n`);
  assert.match(message, /unclosed code fence/);
});

// --- validating the file about to be WRITTEN, not only the one read.
// `findBlock` returning null is not a neutral observation, it is the
// instruction "append at end of file" — and end of file can be inside an
// unterminated fence. Checking the marker set and acting on the write position
// is checking one thing and deciding another.

test('an unclosed fence with no markers refuses instead of writing the block inside the code block', () => {
  // The idiom that made this reachable: a short template ending in an open
  // fence for the author to paste into.
  const { message, exitCode } = malformed('# PR\n\nPaste your logs:\n\n```\n');
  assert.match(message, /pull_request_template\.md/);
  assert.equal(exitCode, 1);
});

test('the append guard fires on the shape the refinement actually decides, not only where a block exists', () => {
  // No block yet, fence above the append point: the one shape where the
  // "no marker in the region" exemption changes the outcome.
  assert.throws(() => wrap('# Team notes\n\n```sh\nnpm test\n', 'NEW'), isRedlineError);
  // And the shape it was narrowed to keep: an unterminated fence BELOW an
  // intact block, where the write is a replace and never enters the region.
  const replaced = wrap(`${BEGIN}\n\nOLD\n\n${END}\n\n# Notes\n\n\`\`\`sh\nnever closed\n`, 'NEW');
  assert.match(replaced, /NEW/);
  assert.ok(replaced.endsWith('```sh\nnever closed\n'));
});

test('a generated body that leaves a fence open is refused before anything is written', () => {
  // I1: standards/ content is emitted verbatim into the body. An unbalanced
  // fence authored there would otherwise write a block nothing can find again,
  // in every onboarded repository.
  const { message } = malformed(null, '# Rules\n\n```sh\nnpm test\n');
  assert.match(message, /pull_request_template\.md/);
  assert.throws(() => wrap('# Existing\n', '# Rules\n\n```sh\nnpm test\n'), isRedlineError);
});

test('the unclosed-fence hint does not tell the operator to move a block that is inside the fence', () => {
  try {
    wrap(`${BEGIN}\n\n\`\`\`\nOLD\n\n${END}\n\nafter\n`, 'NEW');
    throw new Error('expected a refusal');
  } catch (error) {
    assert.ok(isRedlineError(error));
    assert.ok(
      !(error.hint ?? '').includes('move the REDLINE block above it'),
      'the block it names is the one inside the fence — that advice cannot be followed'
    );
    assert.match(error.hint ?? '', /generated block/);
  }
});

// --- fence-parser states that silently appended a second block or refused a
// document that renders correctly.

test('a list-item code fence closed at the list content indent is not read as an unclosed fence', () => {
  const existing = `# Docs\n\n- run this:\n\n- \`\`\`\n  npm test\n  \`\`\`\n\n${BEGIN}\n\nOLD\n\n${END}\n`;
  const out = wrap(existing, 'NEW');
  assert.match(out, /npm test/, 'the list item must survive');
  assert.match(out, /NEW/);
  assert.ok(!out.includes('OLD'));
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1, 'no second block may be appended');
});

test('a fence inside a multi-line HTML comment is not a fence, so the real block is still replaced', () => {
  const existing =
    `# Docs\n\n<!--\n\`\`\`\nan aside\n-->\n\n${BEGIN}\n\nOLD\n\n${END}\n\n` +
    `<!--\n\`\`\`\nanother aside\n-->\n`;
  const out = wrap(existing, 'NEW');
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1, 'the real block must be found, not duplicated');
  assert.match(out, /NEW/);
  assert.ok(!out.includes('OLD'));
});

test('a fence inside an HTML block is not a fence, so no second block is appended beside the real one', () => {
  const existing =
    `<div>\n\`\`\`\n</div>\n\n${BEGIN}\n\nOLD\n\n${END}\n\n` +
    `<div>\n\`\`\`\n</div>\n`;
  const out = wrap(existing, 'NEW');
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1, 'the real block must be found, not abandoned');
  assert.equal(out.split(END).length - 1, 1);
  assert.match(out, /NEW/);
  assert.ok(!out.includes('OLD'));
});

test('markers are still seen inside an HTML block, so suppressing fences there hides nothing', () => {
  const out = wrap(`<div>\n${BEGIN}\n\nOLD\n\n${END}\n</div>\n`, 'NEW');
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1);
  assert.match(out, /NEW/);
});

// --- m4: a marker line prefixed by leading whitespace used to be invisible to
// the scan, so a real block a human tab-indented (a paste, an autoformatter, a
// manual edit) was read as absent and the next run appended a silent second
// block beside it. Detection is now tolerant of leading whitespace; writing is
// not — a found indented block is replaced and re-emitted at column zero.

test('a tab-indented marker pair is found and replaced, not duplicated', () => {
  const existing = `before\n\n\t${BEGIN}\n\n\tOLD\n\n\t${END}\n\nafter\n`;
  const out = wrap(existing, 'NEW');
  // The interior is Redline's to regenerate, same as any replace: OLD does
  // not survive, and the new block lands at column zero, not re-indented.
  assert.equal(out, `before\n\n${BEGIN}\n\nNEW\n\n${END}\n\nafter\n`);
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1, 'no second block may be appended');
  assert.equal(out.split(END).length - 1, 1);
  assert.equal(wrap(out, 'NEW'), out, 'and it is stable across a second run');
});

test('a marker indented with plain spaces is found too', () => {
  const existing = `head\n\n    ${BEGIN}\n\n    OLD\n\n    ${END}\n\ntail\n`;
  const out = wrap(existing, 'NEW');
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1);
  assert.match(out, /NEW/);
  assert.ok(!out.includes('OLD'));
});

test('a tab-indented BEGIN paired with a column-zero END is still found as the one span', () => {
  // Only the BEGIN line picked up the indent — still a single well-formed
  // pair, not an ambiguity, so it replaces rather than refusing.
  const existing = `\t${BEGIN}\n\nOLD\n\n${END}\n`;
  const out = wrap(existing, 'NEW');
  assert.equal(out, `${BEGIN}\n\nNEW\n\n${END}\n`);
});

test('an indented look-alike beside a real column-zero block is refused rather than guessed at', () => {
  // Two BEGINs now — one real, one that only widened detection makes
  // visible. Ambiguous, so the existing duplicate-marker refusal fires
  // rather than either one silently winning.
  const { message } = malformed(`\t${BEGIN}\n\nDOC EXAMPLE\n\n\t${END}\n\n${BEGIN}\n\nOLD\n\n${END}\n`);
  assert.match(message, /2 REDLINE:BEGIN/);
});
