import { test } from 'node:test';
import assert from 'node:assert/strict';
import { isRedlineError } from '../../core/errors.ts';
import { BEGIN, BEGIN_PREFIX, END, findBlock, wrapBlock } from '../markers.ts';

const LABEL = '.github/pull_request_template.md';
const wrap = (existing: string | null, body: string): string => wrapBlock(existing, body, LABEL);

const malformed = (existing: string): { message: string; exitCode: number } => {
  try {
    wrap(existing, 'NEW');
  } catch (error) {
    assert.ok(isRedlineError(error), 'a malformed marker pair must fail as a RedlineError');
    return { message: error.message, exitCode: error.exitCode };
  }
  throw new Error('expected wrapBlock to refuse the file');
};

test('the marker strings are byte-exact', () => {
  assert.equal(BEGIN_PREFIX, '<!-- REDLINE:BEGIN');
  assert.equal(BEGIN, '<!-- REDLINE:BEGIN — generated by Redline. Do not edit inside this block. -->');
  assert.equal(END, '<!-- REDLINE:END -->');
});

test('no existing file yields the block alone', () => {
  assert.equal(wrap(null, 'rules'), `${BEGIN}\n\nrules\n\n${END}\n`);
});

test('an existing file without markers keeps its content and gains the block', () => {
  const out = wrap('# My repo\n\nHand-written.\n', 'rules');
  assert.equal(out, `# My repo\n\nHand-written.\n\n${BEGIN}\n\nrules\n\n${END}\n`);
});

test('an existing block is replaced and surrounding content preserved', () => {
  const existing = `before\n\n${BEGIN}\n\nOLD\n\n${END}\n\nafter\n`;
  const out = wrap(existing, 'NEW');
  assert.equal(out, `before\n\n${BEGIN}\n\nNEW\n\n${END}\n\nafter\n`);
  assert.ok(!out.includes('OLD'));
});

test('content after the end marker survives verbatim, including a second heading', () => {
  const existing = `${BEGIN}\n\nOLD\n\n${END}\n\n## Repo-owned section\n\nkeep me\n`;
  assert.match(wrap(existing, 'NEW'), /## Repo-owned section\n\nkeep me\n$/);
});

test('the body is right-trimmed before wrapping', () => {
  assert.equal(wrap(null, 'rules\n\n\n'), `${BEGIN}\n\nrules\n\n${END}\n`);
});

test('running wrapBlock twice with the same body is idempotent', () => {
  const first = wrap('before\n\nhand-written\n', 'rules');
  assert.equal(wrap(first, 'rules'), first);
});

// The marker text is attribution prose, and it has already been wrong once: it
// named scripts/render.mjs while the CLI's install path writes blocks too.
// Matching on the whole literal makes every future correction a live migration
// hazard — the blocks already on disk in every onboarded repository stop
// matching, and the next run appends a SECOND block beside the first.
test('a block whose BEGIN line differs in its trailing prose is replaced, not duplicated', () => {
  const stale = '<!-- REDLINE:BEGIN — generated by scripts/render.mjs. Do not edit inside this block. -->';
  const out = wrap(`before\n\n${stale}\n\nOLD\n\n${END}\n\nafter\n`, 'NEW');
  assert.equal(out, `before\n\n${BEGIN}\n\nNEW\n\n${END}\n\nafter\n`);
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1, 'exactly one BEGIN marker must survive');
  assert.ok(!out.includes(stale));
});

test('a block written under an older marker text is recognised as owned, not appended to', () => {
  const out = wrap(`<!-- REDLINE:BEGIN — something else entirely -->\n\nOLD\n\n${END}\n`, 'NEW');
  assert.equal(out.split(END).length - 1, 1, 'exactly one END marker must survive');
  assert.ok(out.startsWith(BEGIN));
});

// --- malformed marker pairs. Redline cannot tell which span it owns, so it
// must not guess: no silent repair, no second block, no deletion. Refuse and
// name the file. wrapBlock also writes CLAUDE.md, AGENTS.md and
// .github/copilot-instructions.md in every onboarded repository, so a wrong
// guess here corrupts files across the whole estate, not just this one.

test('END before BEGIN is refused instead of duplicating the span on every run', () => {
  const { message, exitCode } = malformed(`head\n\n${END}\n\nmiddle\n\n${BEGIN}\n\ntail\n`);
  assert.match(message, /pull_request_template\.md/, 'the message must name the file');
  assert.match(message, /REDLINE:END/);
  assert.match(message, /before/);
  assert.equal(exitCode, 1);
});

test('a BEGIN marker with no END is refused instead of losing user content on the second run', () => {
  const { message, exitCode } = malformed(`A\n\n${BEGIN}\n\nUSER STUFF\n`);
  assert.match(message, /pull_request_template\.md/);
  assert.match(message, /REDLINE:BEGIN/);
  assert.equal(exitCode, 1);
});

test('an END marker with no BEGIN is refused', () => {
  const { message } = malformed(`A\n\n${END}\n\nB\n`);
  assert.match(message, /REDLINE:END/);
});

test('two BEGIN markers are refused rather than the first one silently winning', () => {
  const { message } = malformed(`${BEGIN}\n\nONE\n\n${BEGIN}\n\nTWO\n\n${END}\n`);
  assert.match(message, /pull_request_template\.md/);
});

test('two END markers are refused rather than the first one silently winning', () => {
  const { message } = malformed(`${BEGIN}\n\nONE\n\n${END}\n\nmid\n\n${END}\n`);
  assert.match(message, /pull_request_template\.md/);
});

test('a refused file is reported with a hint that tells a human how to fix their own file', () => {
  try {
    wrap(`${BEGIN}\n\nno end\n`, 'NEW');
    throw new Error('expected a refusal');
  } catch (error) {
    assert.ok(isRedlineError(error));
    assert.match(error.hint ?? '', /REDLINE:BEGIN/);
  }
});

// --- a marker quoted rather than written. Matching on the prefix widened this
// sink: any quoted marker text, current or historical, used to be a live target.

test('a marker quoted mid-line in prose is not mistaken for the block', () => {
  const existing = `Docs say the block starts at \`${BEGIN_PREFIX}\` and ends at \`${END}\`.\n`;
  const out = wrap(existing, 'NEW');
  assert.ok(out.startsWith(existing), 'the prose must survive verbatim');
  assert.ok(out.endsWith(`${BEGIN}\n\nNEW\n\n${END}\n`), 'the block is appended, not spliced into the prose');
});

test('a marker inside a fenced code block is not mistaken for the block, and the real one is replaced', () => {
  const existing =
    `# Docs\n\nOur convention:\n\n\`\`\`md\n${BEGIN}\n\nEXAMPLE\n\n${END}\n\`\`\`\n\n` +
    `HUMAN SECTION A\n\n${BEGIN}\n\nOLD\n\n${END}\n\nTail\n`;

  const out = wrap(existing, 'NEW');

  assert.match(out, /HUMAN SECTION A/, 'content between the fence and the real block must survive');
  assert.match(out, /EXAMPLE/, 'the fenced illustration must survive');
  assert.match(out, /Tail\n$/);
  assert.ok(!out.includes('OLD'));
  assert.equal(out.split('NEW').length - 1, 1);
});

test('a tilde-fenced marker is skipped too, and a longer closing fence still closes', () => {
  const existing = `~~~~\n${BEGIN}\nEXAMPLE\n${END}\n~~~~\n\nreal:\n\n${BEGIN}\n\nOLD\n\n${END}\n`;
  const out = wrap(existing, 'NEW');
  assert.match(out, /EXAMPLE/);
  assert.ok(!out.includes('OLD'));
});

// --- byte-level boundaries.

test('an empty file gets the block alone, with no leading blank lines', () => {
  assert.equal(wrap('', 'rules'), `${BEGIN}\n\nrules\n\n${END}\n`);
});

test('a file with no trailing newline keeps its last byte and is separated from the block', () => {
  assert.equal(wrap('X', 'rules'), `X\n\n${BEGIN}\n\nrules\n\n${END}\n`);
});

test('trailing blank lines in the human file are preserved, not trimmed away', () => {
  const existing = 'keep\n\n\n\n';
  const out = wrap(existing, 'rules');
  assert.ok(out.startsWith(existing), 'the append path must be byte-for-byte on the existing content');
  assert.equal(out, `${existing}${BEGIN}\n\nrules\n\n${END}\n`);
});

test('a CRLF file keeps its line endings outside the block on both the append and replace paths', () => {
  const appended = wrap('# Repo\r\n\r\nHand-written.\r\n', 'rules');
  assert.ok(appended.startsWith('# Repo\r\n\r\nHand-written.\r\n'), 'CRLF content must survive verbatim');
  assert.ok(appended.endsWith(`${BEGIN}\n\nrules\n\n${END}\n`));

  const replaced = wrap(`before\r\n\r\n${BEGIN}\r\n\r\nOLD\r\n\r\n${END}\r\n\r\nafter\r\n`, 'NEW');
  assert.ok(replaced.startsWith('before\r\n\r\n'));
  assert.ok(replaced.endsWith('\r\n\r\nafter\r\n'));
  assert.ok(!replaced.includes('OLD'));
});

test('findBlock reports no block for a file that has never been touched', () => {
  assert.equal(findBlock('# Repo\n\nnothing here\n', LABEL), null);
});
