import { test } from 'node:test';
import assert from 'node:assert/strict';
import { BEGIN, BEGIN_PREFIX, END, wrapBlock } from '../markers.ts';

test('the marker strings are byte-exact', () => {
  assert.equal(BEGIN_PREFIX, '<!-- REDLINE:BEGIN');
  assert.equal(BEGIN, '<!-- REDLINE:BEGIN — generated by Redline. Do not edit inside this block. -->');
  assert.equal(END, '<!-- REDLINE:END -->');
});

// The marker text is attribution prose, and it has already been wrong once:
// it named scripts/render.mjs while the CLI's install path writes blocks too.
// Matching on the whole literal makes every future correction a live migration
// hazard — the blocks already on disk in every onboarded repository stop
// matching, and the next run appends a SECOND block beside the first.
test('a block whose BEGIN line differs in its trailing prose is replaced, not duplicated', () => {
  const stale = '<!-- REDLINE:BEGIN — generated by scripts/render.mjs. Do not edit inside this block. -->';
  const existing = `before\n\n${stale}\n\nOLD\n\n${END}\n\nafter\n`;

  const out = wrapBlock(existing, 'NEW');

  assert.equal(out, `before\n\n${BEGIN}\n\nNEW\n\n${END}\n\nafter\n`);
  assert.equal(out.split(BEGIN_PREFIX).length - 1, 1, 'exactly one BEGIN marker must survive');
  assert.ok(!out.includes(stale), 'the stale marker line must be rewritten, not left beside a new one');
  assert.ok(!out.includes('OLD'));
});

test('a block written under an older marker text is recognised as owned, not appended to', () => {
  const stale = '<!-- REDLINE:BEGIN — something else entirely -->';
  const out = wrapBlock(`${stale}\n\nOLD\n\n${END}\n`, 'NEW');
  assert.equal(out.split(END).length - 1, 1, 'exactly one END marker must survive');
  assert.ok(out.startsWith(BEGIN));
});

test('no existing file yields the block alone', () => {
  assert.equal(wrapBlock(null, 'rules'), `${BEGIN}\n\nrules\n\n${END}\n`);
});

test('an existing file without markers keeps its content and gains the block', () => {
  const out = wrapBlock('# My repo\n\nHand-written.\n', 'rules');
  assert.equal(out, `# My repo\n\nHand-written.\n\n${BEGIN}\n\nrules\n\n${END}\n`);
});

test('an existing block is replaced and surrounding content preserved', () => {
  const existing = `before\n\n${BEGIN}\n\nOLD\n\n${END}\n\nafter\n`;
  const out = wrapBlock(existing, 'NEW');
  assert.equal(out, `before\n\n${BEGIN}\n\nNEW\n\n${END}\n\nafter\n`);
  assert.ok(out.includes('before'));
  assert.ok(out.includes('after'));
  assert.ok(!out.includes('OLD'));
});

test('content after the end marker survives verbatim, including a second heading', () => {
  const existing = `${BEGIN}\n\nOLD\n\n${END}\n\n## Repo-owned section\n\nkeep me\n`;
  assert.match(wrapBlock(existing, 'NEW'), /## Repo-owned section\n\nkeep me\n$/);
});

test('a half-open block (BEGIN with no END) is treated as no markers at all', () => {
  const existing = `stuff\n\n${BEGIN}\n\ntruncated\n`;
  const out = wrapBlock(existing, 'NEW');
  assert.ok(out.endsWith(`${BEGIN}\n\nNEW\n\n${END}\n`));
  assert.ok(out.includes('truncated'));
});

test('the body is right-trimmed before wrapping', () => {
  assert.equal(wrapBlock(null, 'rules\n\n\n'), `${BEGIN}\n\nrules\n\n${END}\n`);
});

test('running wrapBlock twice with the same body is idempotent', () => {
  const first = wrapBlock('before\n\nhand-written\n', 'rules');
  const second = wrapBlock(first, 'rules');
  assert.equal(second, first);
});
