import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { isPending } from '../../platforms/types.ts';
import type {
  CapabilityOutcome,
  Change,
  GateOptions,
  InstallResult,
  MergePolicy,
  OwnershipRule,
  Platform,
  PolicyResult,
  PullRequestRef,
  RepoRef,
  SecurityResult,
} from '../../platforms/types.ts';

export interface FakePlatformOptions {
  ref?: RepoRef;
  gate?: CapabilityOutcome[];
  ownership?: CapabilityOutcome[];
  security?: CapabilityOutcome[];
  policy?: CapabilityOutcome[];
  gateFiles?: string[];
  failPullRequest?: boolean;
  // What `readSecurityState` reports back off the host, which is not the same
  // thing as what `enableSecurityFloor` returned when it was applied: an
  // administrator may have granted a capability since. Defaults to `security`.
  securityState?: CapabilityOutcome[];
  // Work that only exists once the pull request does — Azure applies its sync
  // labels there. It is report-only: `.redline.json` is part of the pull
  // request and was written before it, so this can never reach pendingAdmin.
  pullRequestOutcomes?: CapabilityOutcome[];
}

export interface FakePlatform extends Platform {
  // Host settings this fake actually changed. A check-mode call is a plan, not
  // a mutation, and is recorded in `planned` instead — `redline init` must be
  // able to work out that a settled repository needs nothing without changing
  // a single host setting.
  applied: string[];
  planned: string[];
  // Host reads. Separate from `applied` so a test can assert that `--dry-run`
  // touched the network at all, which "no mutation" alone never proved.
  reads: string[];
  lastPolicy: MergePolicy | null;
}

/**
 * The policy a repository has after a default `init`. `readPolicy` returns this
 * until `applyPolicy` overwrites it, so a fresh fake stands in for an already
 * onboarded repository — which is what the verify tests need.
 */
const ADVISORY: MergePolicy = {
  requiredApprovals: 1,
  dismissStaleReviews: true,
  requireCodeOwnerReview: true,
  requireThreadResolution: true,
  requiredChecks: [],
  blocking: false,
};

const ok = (capability: CapabilityOutcome['capability']): CapabilityOutcome => ({
  capability,
  status: 'applied',
  detail: capability,
});

// What the GitHub adapter's caller workflow carries: the reusable-workflow
// reference, which is also how init tells a v3 repository from a 2.1 one.
const GATE_BODY = '# Managed by Redline.\nuses: acme/.github/.github/workflows/redline-gate.yml@main\n';

// Both real adapters sync a pull request template as part of installGate, and
// `redline verify` observes the one the host would serve. A fake that skipped
// it left every onboarded fixture looking like a repository whose template had
// been deleted.
const TEMPLATE_PATH = '.github/pull_request_template.md';
const TEMPLATE_BODY = [
  '# Summary',
  '',
  '<!-- REDLINE:BEGIN — generated by Redline. Do not edit inside this block. -->',
  '',
  '## Launch readiness',
  '',
  '- [ ] Tested',
  '',
  '## Architecture decision',
  '',
  'ADR: `docs/adr/NNNN-*.md`',
  '',
  '<!-- REDLINE:END -->',
  '',
].join('\n');

// Mirrors the real adapters' syncFile: a file whose content already matches is
// not a change, so it never appears in the returned file list.
function seed(cwd: string, relPath: string, body: string, check: boolean): boolean {
  const target = join(cwd, relPath);
  if (existsSync(target) && readFileSync(target, 'utf8') === body) return false;
  if (check) return true;
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, body);
  return true;
}

export function fakePlatform(opts: FakePlatformOptions = {}): FakePlatform {
  const applied: string[] = [];
  const planned: string[] = [];
  const reads: string[] = [];
  const ref: RepoRef = opts.ref ?? {
    host: 'github',
    org: 'acme',
    repo: 'web',
    defaultBranch: 'main',
  };
  const platform: FakePlatform = {
    host: ref.host,
    applied,
    planned,
    reads,
    lastPolicy: ADVISORY,
    localRef(): RepoRef {
      return ref;
    },
    async repoRef(): Promise<RepoRef> {
      reads.push('repoRef');
      return ref;
    },
    async installGate(
      _ref: RepoRef,
      cwd: string,
      _opts: GateOptions,
      check = false
    ): Promise<InstallResult> {
      (check ? planned : applied).push('installGate');
      const files = (opts.gateFiles ?? ['.github/workflows/redline.yml']).filter((rel) =>
        seed(cwd, rel, GATE_BODY, check)
      );
      if (seed(cwd, TEMPLATE_PATH, TEMPLATE_BODY, check)) files.push(TEMPLATE_PATH);
      return { files, outcomes: check ? [] : (opts.gate ?? [ok('labels')]) };
    },
    async applyPolicy(_ref: RepoRef, policy: MergePolicy): Promise<PolicyResult> {
      applied.push('applyPolicy');
      const outcomes = opts.policy ?? [ok('merge-policy'), ok('repo-property')];
      // A refused write changes nothing on the host. Recording the policy
      // anyway modelled a host where the denial still took effect, which is
      // the one state `merge-policy` in pendingAdmin is about — and it is what
      // hid a re-run that never converged when the ruleset was readable but
      // not writable.
      const wrote = !outcomes.some((o) => o.capability === 'merge-policy' && isPending(o));
      if (wrote) platform.lastPolicy = policy;
      return { outcomes, policy };
    },
    async enableSecurityFloor(): Promise<SecurityResult> {
      applied.push('enableSecurityFloor');
      return {
        outcomes: opts.security ?? [ok('secret-scanning'), ok('push-protection'), ok('dependency-alerts')],
      };
    },
    async ensureReviewOwnership(
      _ref: RepoRef,
      cwd: string,
      _rules: OwnershipRule[],
      check = false
    ): Promise<InstallResult> {
      (check ? planned : applied).push('ensureReviewOwnership');
      const seeded = seed(cwd, '.github/CODEOWNERS', '# Managed by Redline.\n', check);
      return {
        files: seeded ? ['.github/CODEOWNERS'] : [],
        outcomes: opts.ownership ?? [ok('review-ownership')],
      };
    },
    async openPullRequest(_ref: RepoRef, _cwd: string, _change: Change): Promise<PullRequestRef> {
      applied.push('openPullRequest');
      if (opts.failPullRequest) throw new Error('nothing to commit');
      return {
        number: 1,
        url: 'https://example/pr/1',
        ...(opts.pullRequestOutcomes ? { outcomes: opts.pullRequestOutcomes } : {}),
      };
    },
    async readPolicy(): Promise<MergePolicy | null> {
      reads.push('readPolicy');
      return platform.lastPolicy;
    },
    async readReportedCheckNames(): Promise<string[]> {
      reads.push('readReportedCheckNames');
      return ['redline-gate / gate'];
    },
    async readSecurityState(): Promise<SecurityResult> {
      reads.push('readSecurityState');
      return {
        outcomes: opts.securityState ??
          opts.security ?? [ok('secret-scanning'), ok('push-protection')],
      };
    },
    async latestPullRequestNumber(): Promise<number | null> {
      reads.push('latestPullRequestNumber');
      return 1;
    },
  };
  return platform;
}
