#!/usr/bin/env node
// Renders the vendor-neutral standards in standards/ into vendor-specific artifacts.
//
//   node scripts/render.mjs --profile web --out ./target-repo
//   node scripts/render.mjs --profile service-java --out . --vendors copilot,agents
//   node scripts/render.mjs --self --check      # CI: fail if committed output is stale
//
// Generated files are owned by Redline. Content outside the REDLINE markers in
// AGENTS.md / CLAUDE.md / copilot-instructions.md belongs to the repo and is preserved.

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const BEGIN = '<!-- REDLINE:BEGIN — generated by scripts/render.mjs. Do not edit inside this block. -->';
const END = '<!-- REDLINE:END -->';
const PREFIX = 'redline-';

const args = process.argv.slice(2);
const flag = (name, fallback = undefined) => {
  const i = args.indexOf(`--${name}`);
  if (i === -1) return fallback;
  const next = args[i + 1];
  return next && !next.startsWith('--') ? next : true;
};

const manifest = JSON.parse(readFileSync(join(ROOT, 'standards/manifest.json'), 'utf8'));

export function resolveProfile(name) {
  const key = manifest.profileAliases[name] ?? name;
  const stacks = manifest.profiles[key];
  if (!stacks) {
    throw new Error(
      `unknown profile "${name}". Known: ${Object.keys(manifest.profiles).join(', ')} ` +
        `(aliases: ${Object.keys(manifest.profileAliases).join(', ')})`
    );
  }
  const out = [];
  const visit = (id) => {
    const stack = manifest.stacks[id];
    if (!stack) throw new Error(`profile "${key}" references unknown stack "${id}"`);
    for (const parent of stack.extends ?? []) visit(parent);
    if (!out.includes(id)) out.push(id);
  };
  stacks.forEach(visit);
  return { profile: key, stacks: out };
}

const read = (relPath) => readFileSync(join(ROOT, relPath), 'utf8').trimEnd();
const stackBody = (id) => read(manifest.stacks[id].source);
const header = (profile, stacks) =>
  `<!-- Redline v${manifest.version} · profile: ${profile} · stacks: ${stacks.join(', ')} -->`;

function wrap(existingPath, body) {
  const block = `${BEGIN}\n\n${body.trimEnd()}\n\n${END}\n`;
  if (!existsSync(existingPath)) return block;
  const current = readFileSync(existingPath, 'utf8');
  const start = current.indexOf(BEGIN);
  const stop = current.indexOf(END);
  if (start === -1 || stop === -1) return `${current.trimEnd()}\n\n${block}`;
  return current.slice(0, start) + block.trimEnd() + current.slice(stop + END.length);
}

// --- vendor renderers -------------------------------------------------------
// Each returns { files: Map<path, contents>, managedGlobs: [dir, matcher] }

const vendors = {
  // GitHub Copilot code review + Copilot Chat.
  // Path-scoped rules use .github/instructions/*.instructions.md with an applyTo glob list.
  copilot({ profile, stacks }) {
    const files = new Map();
    files.set('.github/copilot-instructions.md', {
      merge: true,
      body: `${header(profile, stacks)}\n\n${read(manifest.core.source)}`,
    });
    for (const id of stacks) {
      const stack = manifest.stacks[id];
      files.set(`.github/instructions/${PREFIX}${id}.instructions.md`, {
        body:
          `---\napplyTo: ${JSON.stringify(stack.globs.join(','))}\n---\n\n` +
          `${header(profile, [id])}\n\n${stackBody(id)}`,
      });
    }
    return { files, prune: [['.github/instructions', (f) => f.startsWith(PREFIX) && f.endsWith('.instructions.md')]] };
  },

  // AGENTS.md — the cross-vendor convention read by OpenAI Codex, the Copilot coding
  // agent, Jules, Cursor's agent and others. One file, so stack rules are concatenated
  // with an explicit scope line instead of frontmatter globs.
  agents({ profile, stacks }) {
    // One file, so every stack heading is demoted a level to sit under "# Stack rules".
    const demote = (md) => md.replace(/^(#{1,5}) /gm, '#$1 ');
    const sections = stacks.map((id) => {
      const stack = manifest.stacks[id];
      const scope = stack.globs.map((g) => `\`${g}\``).join(', ');
      return `${demote(stackBody(id))}\n\n_Applies to: ${scope}_`;
    });
    const body = [
      header(profile, stacks),
      '',
      read(manifest.core.source).replace(/^# /, '# '),
      '',
      '---',
      '',
      '# Stack rules',
      '',
      sections.join('\n\n---\n\n'),
    ].join('\n');
    return { files: new Map([['AGENTS.md', { merge: true, body }]]) };
  },

  // Claude Code and Claude in GitHub read CLAUDE.md; keep it a thin import of AGENTS.md
  // so there is exactly one rendered copy of the rules per repo.
  claude() {
    const body = [
      'Engineering standards and review rules for this repository are defined by Redline',
      'and rendered into `AGENTS.md`. They are binding for all work in this repo.',
      '',
      '@AGENTS.md',
    ].join('\n');
    return { files: new Map([['CLAUDE.md', { merge: true, body }]]) };
  },

  cursor({ profile, stacks }) {
    const files = new Map();
    files.set(`.cursor/rules/${PREFIX}core.mdc`, {
      body: `---\ndescription: Redline core standards\nalwaysApply: true\n---\n\n${header(profile, stacks)}\n\n${read(manifest.core.source)}`,
    });
    for (const id of stacks) {
      const stack = manifest.stacks[id];
      files.set(`.cursor/rules/${PREFIX}${id}.mdc`, {
        body: `---\ndescription: Redline ${manifest.stacks[id].title} rules\nglobs: ${stack.globs.join(',')}\nalwaysApply: false\n---\n\n${stackBody(id)}`,
      });
    }
    return { files, prune: [['.cursor/rules', (f) => f.startsWith(PREFIX) && f.endsWith('.mdc')]] };
  },
};

// --- driver -----------------------------------------------------------------

export function render({ profile, vendors: wanted, out, check = false }) {
  const resolved = resolveProfile(profile);
  const selected = wanted ?? Object.entries(manifest.vendors).filter(([, v]) => v.enabled).map(([k]) => k);
  const planned = new Map();
  const prunes = [];

  for (const name of selected) {
    const renderer = vendors[name];
    if (!renderer) throw new Error(`unknown vendor "${name}". Known: ${Object.keys(vendors).join(', ')}`);
    const result = renderer(resolved);
    for (const [path, spec] of result.files) planned.set(path, spec);
    prunes.push(...(result.prune ?? []));
  }

  const stale = [];
  const written = [];

  for (const [relPath, spec] of planned) {
    const target = join(out, relPath);
    const next = spec.merge ? wrap(target, spec.body) : `${spec.body.trimEnd()}\n`;
    const current = existsSync(target) ? readFileSync(target, 'utf8') : null;
    if (current === next) continue;
    if (check) { stale.push(relPath); continue; }
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, next);
    written.push(relPath);
  }

  const removed = [];
  for (const [dir, matches] of prunes) {
    const abs = join(out, dir);
    if (!existsSync(abs)) continue;
    for (const file of readdirSync(abs)) {
      if (!matches(file)) continue;
      if (planned.has(join(dir, file))) continue;
      if (check) { stale.push(`${join(dir, file)} (stale, should be removed)`); continue; }
      rmSync(join(abs, file));
      removed.push(join(dir, file));
    }
  }

  return { ...resolved, written, removed, stale, managed: [...planned.keys()] };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const self = flag('self', false);
  const profile = self ? 'tooling' : flag('profile');
  if (!profile) {
    console.error('usage: render.mjs --profile <name> --out <dir> [--vendors a,b] [--check]');
    console.error(`profiles: ${Object.keys(manifest.profiles).join(', ')}`);
    process.exit(2);
  }
  const vendorArg = flag('vendors');
  const result = render({
    profile,
    vendors: typeof vendorArg === 'string' ? vendorArg.split(',').map((s) => s.trim()) : undefined,
    out: resolve(String(flag('out', self ? ROOT : '.'))),
    check: Boolean(flag('check', false)),
  });

  if (result.stale.length) {
    console.error(`Rendered output is stale. Run: node scripts/render.mjs --self\n  ${result.stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log(`profile ${result.profile} · stacks: ${result.stacks.join(', ')}`);
  result.written.forEach((f) => console.log(`  write  ${f}`));
  result.removed.forEach((f) => console.log(`  prune  ${f}`));
  if (!result.written.length && !result.removed.length) console.log('  up to date');
}
