#!/usr/bin/env bash
# Distributes Redline artifacts to onboarded repos as pull requests, never pushes to
# their default branch.
#
#   ORG=acme scripts/sync.sh                    # sync every repo in sync-targets.txt
#   ORG=acme scripts/sync.sh --dry-run          # render and diff, open nothing
#   ORG=acme scripts/sync.sh --only web-shop    # single repo
#
# Requires: gh authenticated as a token with, on every target repo,
#   contents:write, pull_requests:write, workflows:write
# The workflows permission is mandatory — without it every push that touches
# .github/workflows/redline.yml is rejected and the caller workflow never lands.
set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGETS="${TARGETS:-$BUNDLE_DIR/sync-targets.txt}"
BRANCH="${BRANCH:-redline/sync}"
DRY_RUN=false
ONLY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --only) ONLY="${2:?--only needs a repo name}"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

: "${ORG:?ORG is required}"
command -v gh >/dev/null || { echo "gh is required" >&2; exit 2; }
command -v node >/dev/null || { echo "node is required" >&2; exit 2; }

VERSION=$(node -p "require('$BUNDLE_DIR/standards/manifest.json').version")

ok=(); skipped=(); failed=()
SYNC_RESULT=""

sync_repo() {
  local repo="$1" profile="$2"
  local work; work=$(mktemp -d)
  # shellcheck disable=SC2064  # expand $work now, not at trap time
  trap "rm -rf '$work'" RETURN

  SYNC_RESULT="failed"

  gh repo clone "$ORG/$repo" "$work" -- --depth 1 --quiet || return 1

  # Render the vendor artifacts for this repo's profile. render.mjs preserves anything
  # outside the REDLINE markers and prunes rule files the profile no longer includes,
  # so a repo that changes stack does not keep stale rules.
  node "$BUNDLE_DIR/scripts/render.mjs" --profile "$profile" --out "$work" || return 1

  mkdir -p "$work/.github/workflows"
  cp "$BUNDLE_DIR/.github/pull_request_template.md" "$work/.github/pull_request_template.md"
  sed "s|<org>|$ORG|g" "$BUNDLE_DIR/templates/redline.yml" > "$work/.github/workflows/redline.yml"

  # CODEOWNERS is seeded once and then owned by the team — never overwritten, because
  # ownership is a team decision and clobbering it silently reassigns review duty.
  if [[ ! -f "$work/.github/CODEOWNERS" && ! -f "$work/CODEOWNERS" && ! -f "$work/docs/CODEOWNERS" ]]; then
    sed "s|<org>|$ORG|g" "$BUNDLE_DIR/templates/CODEOWNERS" > "$work/.github/CODEOWNERS"
    echo "    seeded .github/CODEOWNERS (placeholders need filling)"
  fi

  git -C "$work" add -A || return 1
  if git -C "$work" diff --cached --quiet; then
    echo "    up to date"
    SYNC_RESULT="skipped"
    return 0
  fi

  echo "    changes:"
  git -C "$work" diff --cached --stat | sed 's/^/      /'

  if [[ "$DRY_RUN" == true ]]; then
    SYNC_RESULT="ok"
    return 0
  fi

  git -C "$work" checkout -q -B "$BRANCH" || return 1
  git -C "$work" -c user.name="redline-bot" \
    -c user.email="redline-bot@users.noreply.github.com" \
    commit -q -m "chore(redline): sync review standards to v$VERSION

Generated by the Redline source repo. Do not edit the marker blocks by hand;
changes belong in the Redline source repo's standards/ directory." || return 1

  # Fast-forward-only push. If the branch moved underneath us a human is mid-review on
  # it, and force-pushing would silently discard their comments.
  if ! git -C "$work" push -q origin "$BRANCH"; then
    echo "    push rejected — the sync branch has diverged. Resolve $ORG/$repo#$BRANCH by hand." >&2
    return 1
  fi

  local existing
  existing=$(gh pr list --repo "$ORG/$repo" --head "$BRANCH" --state open --json number --jq '.[0].number // ""')
  if [[ -n "$existing" ]]; then
    echo "    updated existing PR #$existing"
  else
    gh pr create --repo "$ORG/$repo" --head "$BRANCH" \
      --title "chore(redline): sync review standards to v$VERSION" \
      --body "Automated sync from the Redline source repo (profile: \`$profile\`, version \`$VERSION\`).

Generated content sits inside \`<!-- REDLINE:BEGIN -->\` markers; anything outside them is yours and was preserved. Rule changes are described in the source repo's CHANGELOG.md.

Merging this keeps your repo's review standards and readiness gate current. If a rule is wrong for this repo, do not edit it here — raise it in the Redline source repo so every repo benefits." \
      --label redline-sync 2>/dev/null \
      || gh pr create --repo "$ORG/$repo" --head "$BRANCH" \
        --title "chore(redline): sync review standards to v$VERSION" \
        --body "Automated sync from the Redline source repo (profile: \`$profile\`, version \`$VERSION\`)."
  fi
  SYNC_RESULT="ok"
}

# Read targets on fd 3 so gh/git inside the loop cannot swallow the target list.
exec 3< "$TARGETS"
while read -r -u 3 repo profile _rest; do
  [[ -z "${repo// /}" || "$repo" == \#* ]] && continue
  [[ -n "$ONLY" && "$repo" != "$ONLY" ]] && continue

  if [[ -z "${profile:-}" ]]; then
    echo "==> $repo — SKIPPED: no profile in sync-targets.txt" >&2
    failed+=("$repo (no profile)")
    continue
  fi

  echo "==> $repo ($profile)"
  # One bad repo must not abort the remaining hundreds. Calling inside `if` suspends
  # errexit for the function body, so every fallible step inside returns explicitly.
  if sync_repo "$repo" "$profile"; then
    case "$SYNC_RESULT" in
      ok) ok+=("$repo") ;;
      skipped) skipped+=("$repo") ;;
      *) failed+=("$repo") ;;
    esac
  else
    echo "    FAILED" >&2
    failed+=("$repo")
  fi
done
exec 3<&-

echo
echo "synced:  ${#ok[@]}   up-to-date: ${#skipped[@]}   failed: ${#failed[@]}"
if [[ ${#failed[@]} -gt 0 ]]; then
  printf 'failed: %s\n' "${failed[*]}" >&2
  exit 1
fi
