import { isSeverity, type Severity } from '../core/severity.ts';

// The published findings schema: model → CLI.
//
// The model returns JSON against this. The CLI validates it and renders the
// `Redline/<SEVERITY> [rule-id]:` lines itself. **One renderer.** The comment
// contract is generated by code and never free-typed by a model — a model that
// writes the prefix itself will eventually write a severity that does not exist,
// or an id it invented, and every aggregate keyed on that line becomes fiction.

export interface ReviewFinding {
  rule: string;
  severity: Severity;
  file: string;
  line: number;
  problem: string;
  fix: string;
}

export interface ParsedReview {
  findings: ReviewFinding[];
  // A finding the model produced that this refused, and why. Reported rather than
  // dropped: a model that keeps citing rules that do not exist is a fact about
  // the prompt, and silently discarding them hides it.
  rejected: { raw: unknown; reason: string }[];
}

export const SCHEMA_DESCRIPTION = `{
  "findings": [
    {
      "rule": "<stack>/<slug>, exactly as written in the rules above",
      "severity": "BLOCKER" | "HIGH" | "SUGGESTION",
      "file": "path/as/given/in/the/diff.ts",
      "line": <line number in the new file>,
      "problem": "one sentence: what breaks, and the input that breaks it",
      "fix": "one sentence: the concrete change"
    }
  ]
}`;

/**
 * Validate a model's JSON against the schema.
 *
 * `knownRules` is the applicable rule set. A finding citing a rule outside it is
 * rejected — not corrected, not passed through. A model that cites a rule the
 * prompt did not contain has not applied the standard, it has recalled one, and
 * the id is what every measurement is keyed on.
 */
export function parseReview(raw: string, knownRules: Set<string>): ParsedReview {
  const findings: ReviewFinding[] = [];
  const rejected: ParsedReview['rejected'] = [];

  let parsed: unknown;
  try {
    // A model will wrap JSON in a fence more often than not. Tolerating that is
    // not the same as tolerating malformed output.
    const fenced = /```(?:json)?\s*([\s\S]*?)```/.exec(raw);
    parsed = JSON.parse(fenced?.[1] ?? raw);
  } catch (error) {
    return {
      findings,
      rejected: [{ raw, reason: `not valid JSON: ${error instanceof Error ? error.message : String(error)}` }],
    };
  }

  const list = (parsed as { findings?: unknown })?.findings;
  if (!Array.isArray(list)) {
    return { findings, rejected: [{ raw: parsed, reason: 'no "findings" array' }] };
  }

  for (const item of list) {
    const f = item as Record<string, unknown>;
    const reject = (reason: string): void => {
      rejected.push({ raw: item, reason });
    };

    if (typeof f['rule'] !== 'string' || !knownRules.has(f['rule'])) {
      reject(`cites "${String(f['rule'])}", which is not one of the rules this review was given`);
      continue;
    }
    if (!isSeverity(f['severity'])) {
      reject(`severity "${String(f['severity'])}" is not BLOCKER, HIGH or SUGGESTION`);
      continue;
    }
    if (typeof f['file'] !== 'string' || f['file'] === '') {
      reject('no file');
      continue;
    }
    const line = typeof f['line'] === 'number' ? f['line'] : Number.parseInt(String(f['line']), 10);
    if (!Number.isInteger(line) || line < 1) {
      reject(`line "${String(f['line'])}" is not a line number`);
      continue;
    }
    if (typeof f['problem'] !== 'string' || f['problem'].trim() === '') {
      reject('no problem statement — a finding nobody can act on is not a finding');
      continue;
    }

    findings.push({
      rule: f['rule'],
      severity: f['severity'],
      file: f['file'],
      line,
      problem: f['problem'].trim(),
      fix: typeof f['fix'] === 'string' ? f['fix'].trim() : '',
    });
  }

  return { findings, rejected };
}

/** The output contract. Rendered here and nowhere else. */
export function renderFinding(finding: ReviewFinding): string {
  const body = finding.fix ? `${finding.problem} ${finding.fix}` : finding.problem;
  return `Redline/${finding.severity} [${finding.rule}]: ${body}`;
}
